name: dmri_seg

channels:
    - conda-forge
    - pnlbwh

dependencies:
    - python==3.6
    - tensorflow==1.12.0
    - keras==2.2.4
    - numpy==1.16.4
    - nibabel==2.2.1
    - ants
    - pip
    - pip:
        - git+https://github.com/pnlbwh/conversion.git
