name: dmri_seg
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - cudnn
  - nibabel
  - gputil
  - ants
  - pip
  - pip:
    - tensorflow==2.10.0
    - scikit-image
    - git+https://github.com/pnlbwh/conversion.git
